test:
	/opt/homebrew/opt/python@3.8/libexec/bin/python interpreter.py -test exampleProgram_combined.py0
	/opt/homebrew/opt/python@3.8/libexec/bin/python interpreter.py -test exampleProgram_functions.py0
	/opt/homebrew/opt/python@3.8/libexec/bin/python interpreter.py -test exampleProgram_while.py0
	/opt/homebrew/opt/python@3.8/libexec/bin/python interpreter.py -test exampleProgram-1.py0
	/opt/homebrew/opt/python@3.8/libexec/bin/python interpreter.py -test exampleProgram.py0
	/opt/homebrew/opt/python@3.8/libexec/bin/python interpreter.py -test helloWorld.py0
	/opt/homebrew/opt/python@3.8/libexec/bin/python interpreter.py -test ifelse.py0
	/opt/homebrew/opt/python@3.8/libexec/bin/python interpreter.py -test newFuncs.py0
	/opt/homebrew/opt/python@3.8/libexec/bin/python interpreter.py -test test.py0
	/opt/homebrew/opt/python@3.8/libexec/bin/python interpreter.py -test test_forin.py0