test:
	python3 interpreter.py -test exampleProgram_combined.py0
	python3 interpreter.py -test exampleProgram_while.py0
	python3 interpreter.py -test exampleProgram-1.py0
	python3 interpreter.py -test exampleProgram.py0
	python3 interpreter.py -test helloWorld.py0
	python3 interpreter.py -test ifelse.py0
	python3 interpreter.py -test newFuncs.py0
	python3 interpreter.py -test test.py0